
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gate-way-service-demo
  cloud:
    gateway:
      routes:
        - id: counterService
          uri: lb://COUNTER-SERVICE-DEMO
          predicates:
            - Path=/counter/**
